<?php

namespace Database\Seeders;

use App\Models\Regency;
use Illuminate\Database\Seeder;

class RegencySeeder extends Seeder
{
    public function run(): void
    {
        $regencies = [
            ['code' => '1101', 'name' => 'Aceh Barat', 'type' => 'Kabupaten', 'province' => 'Aceh'],
            ['code' => '1171', 'name' => 'Banda Aceh', 'type' => 'Kota', 'province' => 'Aceh'],
            ['code' => '1172', 'name' => 'Sabang', 'type' => 'Kota', 'province' => 'Aceh'],
            ['code' => '1173', 'name' => 'Langsa', 'type' => 'Kota', 'province' => 'Aceh'],
            ['code' => '1174', 'name' => 'Lhokseumawe', 'type' => 'Kota', 'province' => 'Aceh'],
            ['code' => '1175', 'name' => 'Subulussalam', 'type' => 'Kota', 'province' => 'Aceh'],
            ['code' => '1201', 'name' => 'Tapanuli Tengah', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1202', 'name' => 'Tapanuli Utara', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1203', 'name' => 'Tapanuli Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1204', 'name' => 'Nias', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1205', 'name' => 'Langkat', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1206', 'name' => 'Karo', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1207', 'name' => 'Deli Serdang', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1208', 'name' => 'Simalungun', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1209', 'name' => 'Asahan', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1210', 'name' => 'Labuhanbatu', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1211', 'name' => 'Dairi', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1212', 'name' => 'Toba Samosir', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1213', 'name' => 'Mandailing Natal', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1214', 'name' => 'Nias Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1215', 'name' => 'Pakpak Bharat', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1216', 'name' => 'Humbang Hasundutan', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1217', 'name' => 'Samosir', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1218', 'name' => 'Serdang Bedagai', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1219', 'name' => 'Batu Bara', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1220', 'name' => 'Padang Lawas Utara', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1221', 'name' => 'Padang Lawas', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1222', 'name' => 'Labuhanbatu Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1223', 'name' => 'Labuhanbatu Utara', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1224', 'name' => 'Nias Utara', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1225', 'name' => 'Nias Barat', 'type' => 'Kabupaten', 'province' => 'Sumatera Utara'],
            ['code' => '1271', 'name' => 'Medan', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1272', 'name' => 'Pematangsiantar', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1273', 'name' => 'Sibolga', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1274', 'name' => 'Tanjungbalai', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1275', 'name' => 'Binjai', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1276', 'name' => 'Tebing Tinggi', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1277', 'name' => 'Padangsidimpuan', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1278', 'name' => 'Gunungsitoli', 'type' => 'Kota', 'province' => 'Sumatera Utara'],
            ['code' => '1301', 'name' => 'Pesisir Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1302', 'name' => 'Solok', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1303', 'name' => 'Sijunjung', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1304', 'name' => 'Tanah Datar', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1305', 'name' => 'Padang Pariaman', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1306', 'name' => 'Agam', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1307', 'name' => 'Lima Puluh Kota', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1308', 'name' => 'Pasaman', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1309', 'name' => 'Kepulauan Mentawai', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1310', 'name' => 'Dharmasraya', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1311', 'name' => 'Solok Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1312', 'name' => 'Pasaman Barat', 'type' => 'Kabupaten', 'province' => 'Sumatera Barat'],
            ['code' => '1371', 'name' => 'Padang', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1372', 'name' => 'Solok', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1373', 'name' => 'Sawahlunto', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1374', 'name' => 'Padangpanjang', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1375', 'name' => 'Bukittinggi', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1376', 'name' => 'Payakumbuh', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1377', 'name' => 'Pariaman', 'type' => 'Kota', 'province' => 'Sumatera Barat'],
            ['code' => '1401', 'name' => 'Kampar', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1402', 'name' => 'Indragiri Hulu', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1403', 'name' => 'Bengkalis', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1404', 'name' => 'Indragiri Hilir', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1405', 'name' => 'Pelalawan', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1406', 'name' => 'Rokan Hulu', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1407', 'name' => 'Rokan Hilir', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1408', 'name' => 'Siak', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1409', 'name' => 'Kuantan Singingi', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1410', 'name' => 'Kepulauan Meranti', 'type' => 'Kabupaten', 'province' => 'Riau'],
            ['code' => '1471', 'name' => 'Pekanbaru', 'type' => 'Kota', 'province' => 'Riau'],
            ['code' => '1472', 'name' => 'Dumai', 'type' => 'Kota', 'province' => 'Riau'],
            ['code' => '1501', 'name' => 'Kerinci', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1502', 'name' => 'Merangin', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1503', 'name' => 'Sarolangun', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1504', 'name' => 'Batanghari', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1505', 'name' => 'Muaro Jambi', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1506', 'name' => 'Tanjung Jabung Timur', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1507', 'name' => 'Tanjung Jabung Barat', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1508', 'name' => 'Tebo', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1509', 'name' => 'Bungo', 'type' => 'Kabupaten', 'province' => 'Jambi'],
            ['code' => '1571', 'name' => 'Jambi', 'type' => 'Kota', 'province' => 'Jambi'],
            ['code' => '1572', 'name' => 'Sungai Penuh', 'type' => 'Kota', 'province' => 'Jambi'],
            ['code' => '1601', 'name' => 'Ogan Komering Ulu', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1602', 'name' => 'Ogan Komering Ilir', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1603', 'name' => 'Muara Enim', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1604', 'name' => 'Lahat', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1605', 'name' => 'Musi Rawas', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1606', 'name' => 'Musi Banyuasin', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1607', 'name' => 'Banyuasin', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1608', 'name' => 'Ogan Komering Ulu Selatan', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1609', 'name' => 'Ogan Komering Ulu Timur', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1610', 'name' => 'Ogan Ilir', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1611', 'name' => 'Empat Lawang', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1612', 'name' => 'Penukal Abab Lematang Ilir', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1613', 'name' => 'Musi Rawas Utara', 'type' => 'Kabupaten', 'province' => 'Sumatera Selatan'],
            ['code' => '1671', 'name' => 'Palembang', 'type' => 'Kota', 'province' => 'Sumatera Selatan'],
            ['code' => '1672', 'name' => 'Prabumulih', 'type' => 'Kota', 'province' => 'Sumatera Selatan'],
            ['code' => '1673', 'name' => 'Pagar Alam', 'type' => 'Kota', 'province' => 'Sumatera Selatan'],
            ['code' => '1674', 'name' => 'Lubuklinggau', 'type' => 'Kota', 'province' => 'Sumatera Selatan'],
            ['code' => '1701', 'name' => 'Bengkulu Selatan', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1702', 'name' => 'Rejang Lebong', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1703', 'name' => 'Bengkulu Utara', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1704', 'name' => 'Kaur', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1705', 'name' => 'Seluma', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1706', 'name' => 'Mukomuko', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1707', 'name' => 'Lebong', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1708', 'name' => 'Kepahiang', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1709', 'name' => 'Bengkulu Tengah', 'type' => 'Kabupaten', 'province' => 'Bengkulu'],
            ['code' => '1771', 'name' => 'Bengkulu', 'type' => 'Kota', 'province' => 'Bengkulu'],
            ['code' => '1801', 'name' => 'Lampung Barat', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1802', 'name' => 'Lampung Selatan', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1803', 'name' => 'Lampung Tengah', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1804', 'name' => 'Lampung Utara', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1805', 'name' => 'Tulang Bawang', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1806', 'name' => 'Tanggamus', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1807', 'name' => 'Lampung Timur', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1808', 'name' => 'Way Kanan', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1809', 'name' => 'Pesawaran', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1810', 'name' => 'Pringsewu', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1811', 'name' => 'Mesuji', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1812', 'name' => 'Tulang Bawang Barat', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1813', 'name' => 'Pesisir Barat', 'type' => 'Kabupaten', 'province' => 'Lampung'],
            ['code' => '1871', 'name' => 'Bandar Lampung', 'type' => 'Kota', 'province' => 'Lampung'],
            ['code' => '1872', 'name' => 'Metro', 'type' => 'Kota', 'province' => 'Lampung'],
            ['code' => '1901', 'name' => 'Bangka', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1902', 'name' => 'Belitung', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1903', 'name' => 'Bangka Barat', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1904', 'name' => 'Bangka Tengah', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1905', 'name' => 'Bangka Selatan', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1906', 'name' => 'Belitung Timur', 'type' => 'Kabupaten', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '1971', 'name' => 'Pangkalpinang', 'type' => 'Kota', 'province' => 'Kepulauan Bangka Belitung'],
            ['code' => '2101', 'name' => 'Bintan', 'type' => 'Kabupaten', 'province' => 'Kepulauan Riau'],
            ['code' => '2102', 'name' => 'Karimun', 'type' => 'Kabupaten', 'province' => 'Kepulauan Riau'],
            ['code' => '2103', 'name' => 'Natuna', 'type' => 'Kabupaten', 'province' => 'Kepulauan Riau'],
            ['code' => '2104', 'name' => 'Lingga', 'type' => 'Kabupaten', 'province' => 'Kepulauan Riau'],
            ['code' => '2105', 'name' => 'Kepulauan Anambas', 'type' => 'Kabupaten', 'province' => 'Kepulauan Riau'],
            ['code' => '2171', 'name' => 'Batam', 'type' => 'Kota', 'province' => 'Kepulauan Riau'],
            ['code' => '2172', 'name' => 'Tanjungpinang', 'type' => 'Kota', 'province' => 'Kepulauan Riau'],
            ['code' => '3101', 'name' => 'Kepulauan Seribu', 'type' => 'Kabupaten', 'province' => 'DKI Jakarta'],
            ['code' => '3171', 'name' => 'Jakarta Pusat', 'type' => 'Kota', 'province' => 'DKI Jakarta'],
            ['code' => '3172', 'name' => 'Jakarta Utara', 'type' => 'Kota', 'province' => 'DKI Jakarta'],
            ['code' => '3173', 'name' => 'Jakarta Barat', 'type' => 'Kota', 'province' => 'DKI Jakarta'],
            ['code' => '3174', 'name' => 'Jakarta Selatan', 'type' => 'Kota', 'province' => 'DKI Jakarta'],
            ['code' => '3175', 'name' => 'Jakarta Timur', 'type' => 'Kota', 'province' => 'DKI Jakarta'],
            ['code' => '3201', 'name' => 'Bogor', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3202', 'name' => 'Sukabumi', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3203', 'name' => 'Cianjur', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3204', 'name' => 'Bandung', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3205', 'name' => 'Garut', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3206', 'name' => 'Tasikmalaya', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3207', 'name' => 'Ciamis', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3208', 'name' => 'Kuningan', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3209', 'name' => 'Cirebon', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3210', 'name' => 'Majalengka', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3211', 'name' => 'Sumedang', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3212', 'name' => 'Indramayu', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3213', 'name' => 'Subang', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3214', 'name' => 'Purwakarta', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3215', 'name' => 'Karawang', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3216', 'name' => 'Bekasi', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3217', 'name' => 'Bandung Barat', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3218', 'name' => 'Pangandaran', 'type' => 'Kabupaten', 'province' => 'Jawa Barat'],
            ['code' => '3271', 'name' => 'Bogor', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3272', 'name' => 'Sukabumi', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3273', 'name' => 'Bandung', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3274', 'name' => 'Cirebon', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3275', 'name' => 'Bekasi', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3276', 'name' => 'Depok', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3277', 'name' => 'Cimahi', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3278', 'name' => 'Tasikmalaya', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3279', 'name' => 'Banjar', 'type' => 'Kota', 'province' => 'Jawa Barat'],
            ['code' => '3301', 'name' => 'Cilacap', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3302', 'name' => 'Banyumas', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3303', 'name' => 'Purbalingga', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3304', 'name' => 'Banjarnegara', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3305', 'name' => 'Kebumen', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3306', 'name' => 'Purworejo', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3307', 'name' => 'Wonosobo', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3308', 'name' => 'Magelang', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3309', 'name' => 'Boyolali', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3310', 'name' => 'Klaten', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3311', 'name' => 'Sukoharjo', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3312', 'name' => 'Wonogiri', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3313', 'name' => 'Karanganyar', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3314', 'name' => 'Sragen', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3315', 'name' => 'Grobogan', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3316', 'name' => 'Blora', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3317', 'name' => 'Rembang', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3318', 'name' => 'Pati', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3319', 'name' => 'Kudus', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3320', 'name' => 'Jepara', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3321', 'name' => 'Demak', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3322', 'name' => 'Semarang', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3323', 'name' => 'Temanggung', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3324', 'name' => 'Kendal', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3325', 'name' => 'Batang', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3326', 'name' => 'Pekalongan', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3327', 'name' => 'Pemalang', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3328', 'name' => 'Tegal', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3329', 'name' => 'Brebes', 'type' => 'Kabupaten', 'province' => 'Jawa Tengah'],
            ['code' => '3371', 'name' => 'Magelang', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3372', 'name' => 'Surakarta (Solo)', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3373', 'name' => 'Salatiga', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3374', 'name' => 'Semarang', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3375', 'name' => 'Pekalongan', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3376', 'name' => 'Tegal', 'type' => 'Kota', 'province' => 'Jawa Tengah'],
            ['code' => '3401', 'name' => 'Kulon Progo', 'type' => 'Kabupaten', 'province' => 'Daerah Istimewa Yogyakarta'],
            ['code' => '3402', 'name' => 'Bantul', 'type' => 'Kabupaten', 'province' => 'Daerah Istimewa Yogyakarta'],
            ['code' => '3403', 'name' => 'Gunung Kidul', 'type' => 'Kabupaten', 'province' => 'Daerah Istimewa Yogyakarta'],
            ['code' => '3404', 'name' => 'Sleman', 'type' => 'Kabupaten', 'province' => 'Daerah Istimewa Yogyakarta'],
            ['code' => '3471', 'name' => 'Yogyakarta', 'type' => 'Kota', 'province' => 'Daerah Istimewa Yogyakarta'],
            ['code' => '3501', 'name' => 'Pacitan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3502', 'name' => 'Ponorogo', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3503', 'name' => 'Trenggalek', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3504', 'name' => 'Tulungagung', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3505', 'name' => 'Blitar', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3506', 'name' => 'Kediri', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3507', 'name' => 'Malang', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3508', 'name' => 'Lumajang', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3509', 'name' => 'Jember', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3510', 'name' => 'Banyuwangi', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3511', 'name' => 'Bondowoso', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3512', 'name' => 'Situbondo', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3513', 'name' => 'Probolinggo', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3514', 'name' => 'Pasuruan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3515', 'name' => 'Sidoarjo', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3516', 'name' => 'Mojokerto', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3517', 'name' => 'Jombang', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3518', 'name' => 'Nganjuk', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3519', 'name' => 'Madiun', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3520', 'name' => 'Magetan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3521', 'name' => 'Ngawi', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3522', 'name' => 'Bojonegoro', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3523', 'name' => 'Tuban', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3524', 'name' => 'Lamongan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3525', 'name' => 'Gresik', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3526', 'name' => 'Bangkalan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3527', 'name' => 'Sampang', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3528', 'name' => 'Pamekasan', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3529', 'name' => 'Sumenep', 'type' => 'Kabupaten', 'province' => 'Jawa Timur'],
            ['code' => '3571', 'name' => 'Kediri', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3572', 'name' => 'Blitar', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3573', 'name' => 'Malang', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3574', 'name' => 'Probolinggo', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3575', 'name' => 'Pasuruan', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3576', 'name' => 'Mojokerto', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3577', 'name' => 'Madiun', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3578', 'name' => 'Surabaya', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '3579', 'name' => 'Batu', 'type' => 'Kota', 'province' => 'Jawa Timur'],
            ['code' => '5101', 'name' => 'Jembrana', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5102', 'name' => 'Tabanan', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5103', 'name' => 'Badung', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5104', 'name' => 'Gianyar', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5105', 'name' => 'Klungkung', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5106', 'name' => 'Bangli', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5107', 'name' => 'Karangasem', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5108', 'name' => 'Buleleng', 'type' => 'Kabupaten', 'province' => 'Bali'],
            ['code' => '5171', 'name' => 'Denpasar', 'type' => 'Kota', 'province' => 'Bali'],
            ['code' => '5201', 'name' => 'Lombok Barat', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5202', 'name' => 'Lombok Tengah', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5203', 'name' => 'Lombok Timur', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5204', 'name' => 'Sumbawa', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5205', 'name' => 'Dompu', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5206', 'name' => 'Bima', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5207', 'name' => 'Sumbawa Barat', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5208', 'name' => 'Lombok Utara', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5271', 'name' => 'Mataram', 'type' => 'Kota', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5272', 'name' => 'Bima', 'type' => 'Kota', 'province' => 'Nusa Tenggara Barat'],
            ['code' => '5301', 'name' => 'Kupang', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5302', 'name' => 'Timor Tengah Selatan', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5303', 'name' => 'Timor Tengah Utara', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5304', 'name' => 'Belu', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5305', 'name' => 'Alor', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5306', 'name' => 'Flores Timur', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5307', 'name' => 'Sikka', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5308', 'name' => 'Ende', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5309', 'name' => 'Ngada', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5310', 'name' => 'Manggarai', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5311', 'name' => 'Sumba Timur', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5312', 'name' => 'Sumba Barat', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5313', 'name' => 'Lembata', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5314', 'name' => 'Rote Ndao', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5315', 'name' => 'Manggarai Barat', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5316', 'name' => 'Nagekeo', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5317', 'name' => 'Sumba Tengah', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5318', 'name' => 'Sumba Barat Daya', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5319', 'name' => 'Manggarai Timur', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5320', 'name' => 'Sabu Raijua', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5321', 'name' => 'Malaka', 'type' => 'Kabupaten', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '5371', 'name' => 'Kupang', 'type' => 'Kota', 'province' => 'Nusa Tenggara Timur'],
            ['code' => '6101', 'name' => 'Sambas', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6102', 'name' => 'Mempawah', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6103', 'name' => 'Sanggau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6104', 'name' => 'Ketapang', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6105', 'name' => 'Sintang', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6106', 'name' => 'Kapuas Hulu', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6107', 'name' => 'Bengkayang', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6108', 'name' => 'Landak', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6109', 'name' => 'Sekadau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6110', 'name' => 'Melawi', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6111', 'name' => 'Kayong Utara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6112', 'name' => 'Kubu Raya', 'type' => 'Kabupaten', 'province' => 'Kalimantan Barat'],
            ['code' => '6171', 'name' => 'Pontianak', 'type' => 'Kota', 'province' => 'Kalimantan Barat'],
            ['code' => '6172', 'name' => 'Singkawang', 'type' => 'Kota', 'province' => 'Kalimantan Barat'],
            ['code' => '6201', 'name' => 'Kotawaringin Barat', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6202', 'name' => 'Kotawaringin Timur', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6203', 'name' => 'Kapuas', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6204', 'name' => 'Barito Selatan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6205', 'name' => 'Barito Utara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6206', 'name' => 'Katingan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6207', 'name' => 'Seruyan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6208', 'name' => 'Sukamara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6209', 'name' => 'Lamandau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6210', 'name' => 'Gunung Mas', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6211', 'name' => 'Pulang Pisau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6212', 'name' => 'Murung Raya', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6213', 'name' => 'Barito Timur', 'type' => 'Kabupaten', 'province' => 'Kalimantan Tengah'],
            ['code' => '6271', 'name' => 'Palangka Raya', 'type' => 'Kota', 'province' => 'Kalimantan Tengah'],
            ['code' => '6301', 'name' => 'Tanah Laut', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6302', 'name' => 'Kotabaru', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6303', 'name' => 'Banjar', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6304', 'name' => 'Barito Kuala', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6305', 'name' => 'Tapin', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6306', 'name' => 'Hulu Sungai Selatan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6307', 'name' => 'Hulu Sungai Tengah', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6308', 'name' => 'Hulu Sungai Utara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6309', 'name' => 'Tabalong', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6310', 'name' => 'Tanah Bumbu', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6311', 'name' => 'Balangan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Selatan'],
            ['code' => '6371', 'name' => 'Banjarmasin', 'type' => 'Kota', 'province' => 'Kalimantan Selatan'],
            ['code' => '6372', 'name' => 'Banjarbaru', 'type' => 'Kota', 'province' => 'Kalimantan Selatan'],
            ['code' => '6401', 'name' => 'Paser', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6402', 'name' => 'Kutai Kartanegara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6403', 'name' => 'Berau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6404', 'name' => 'Kutai Barat', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6405', 'name' => 'Kutai Timur', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6406', 'name' => 'Penajam Paser Utara', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6407', 'name' => 'Mahakam Ulu', 'type' => 'Kabupaten', 'province' => 'Kalimantan Timur'],
            ['code' => '6471', 'name' => 'Balikpapan', 'type' => 'Kota', 'province' => 'Kalimantan Timur'],
            ['code' => '6472', 'name' => 'Samarinda', 'type' => 'Kota', 'province' => 'Kalimantan Timur'],
            ['code' => '6473', 'name' => 'Bontang', 'type' => 'Kota', 'province' => 'Kalimantan Timur'],
            ['code' => '6474', 'name' => 'Nusantara (IKN)', 'type' => 'Kota', 'province' => 'Kalimantan Timur'],
            ['code' => '6501', 'name' => 'Malinau', 'type' => 'Kabupaten', 'province' => 'Kalimantan Utara'],
            ['code' => '6502', 'name' => 'Bulungan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Utara'],
            ['code' => '6503', 'name' => 'Tana Tidung', 'type' => 'Kabupaten', 'province' => 'Kalimantan Utara'],
            ['code' => '6504', 'name' => 'Nunukan', 'type' => 'Kabupaten', 'province' => 'Kalimantan Utara'],
            ['code' => '6571', 'name' => 'Tarakan', 'type' => 'Kota', 'province' => 'Kalimantan Utara'],
            ['code' => '7101', 'name' => 'Bolaang Mongondow', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7102', 'name' => 'Minahasa', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7103', 'name' => 'Kepulauan Sangihe', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7104', 'name' => 'Kepulauan Talaud', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7105', 'name' => 'Minahasa Selatan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7106', 'name' => 'Minahasa Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7107', 'name' => 'Minahasa Tenggara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7108', 'name' => 'Bolaang Mongondow Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7109', 'name' => 'Kepulauan Siau Tagulandang Biaro', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7110', 'name' => 'Bolaang Mongondow Timur', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7111', 'name' => 'Bolaang Mongondow Selatan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Utara'],
            ['code' => '7171', 'name' => 'Manado', 'type' => 'Kota', 'province' => 'Sulawesi Utara'],
            ['code' => '7172', 'name' => 'Bitung', 'type' => 'Kota', 'province' => 'Sulawesi Utara'],
            ['code' => '7173', 'name' => 'Tomohon', 'type' => 'Kota', 'province' => 'Sulawesi Utara'],
            ['code' => '7174', 'name' => 'Kotamobagu', 'type' => 'Kota', 'province' => 'Sulawesi Utara'],
            ['code' => '7201', 'name' => 'Banggai', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7202', 'name' => 'Poso', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7203', 'name' => 'Donggala', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7204', 'name' => 'Toli-Toli', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7205', 'name' => 'Buol', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7206', 'name' => 'Morowali', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7207', 'name' => 'Banggai Kepulauan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7208', 'name' => 'Parigi Moutong', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7209', 'name' => 'Tojo Una-Una', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7210', 'name' => 'Sigi', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7211', 'name' => 'Banggai Laut', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7212', 'name' => 'Morowali Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tengah'],
            ['code' => '7271', 'name' => 'Palu', 'type' => 'Kota', 'province' => 'Sulawesi Tengah'],
            ['code' => '7301', 'name' => 'Selayar', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7302', 'name' => 'Bulukumba', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7303', 'name' => 'Bantaeng', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7304', 'name' => 'Jeneponto', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7305', 'name' => 'Takalar', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7306', 'name' => 'Gowa', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7307', 'name' => 'Sinjai', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7308', 'name' => 'Bone', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7309', 'name' => 'Maros', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7310', 'name' => 'Pangkajene Kepulauan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7311', 'name' => 'Barru', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7312', 'name' => 'Soppeng', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7313', 'name' => 'Wajo', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7314', 'name' => 'Sidenreng Rappang', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7315', 'name' => 'Pinrang', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7316', 'name' => 'Enrekang', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7317', 'name' => 'Luwu', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7318', 'name' => 'Tana Toraja', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7319', 'name' => 'Luwu Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7320', 'name' => 'Luwu Timur', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7321', 'name' => 'Toraja Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Selatan'],
            ['code' => '7371', 'name' => 'Makassar', 'type' => 'Kota', 'province' => 'Sulawesi Selatan'],
            ['code' => '7372', 'name' => 'Parepare', 'type' => 'Kota', 'province' => 'Sulawesi Selatan'],
            ['code' => '7373', 'name' => 'Palopo', 'type' => 'Kota', 'province' => 'Sulawesi Selatan'],
            ['code' => '7401', 'name' => 'Kolaka', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7402', 'name' => 'Kendari', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7403', 'name' => 'Muna', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7404', 'name' => 'Buton', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7405', 'name' => 'Konawe Selatan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7406', 'name' => 'Bombana', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7407', 'name' => 'Wakatobi', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7408', 'name' => 'Kolaka Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7409', 'name' => 'Konawe Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7410', 'name' => 'Buton Utara', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7411', 'name' => 'Kolaka Timur', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7412', 'name' => 'Konawe Kepulauan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7413', 'name' => 'Muna Barat', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7414', 'name' => 'Buton Tengah', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7415', 'name' => 'Buton Selatan', 'type' => 'Kabupaten', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7471', 'name' => 'Kendari', 'type' => 'Kota', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7472', 'name' => 'Baubau', 'type' => 'Kota', 'province' => 'Sulawesi Tenggara'],
            ['code' => '7501', 'name' => 'Gorontalo', 'type' => 'Kabupaten', 'province' => 'Gorontalo'],
            ['code' => '7502', 'name' => 'Boalemo', 'type' => 'Kabupaten', 'province' => 'Gorontalo'],
            ['code' => '7503', 'name' => 'Bone Bolango', 'type' => 'Kabupaten', 'province' => 'Gorontalo'],
            ['code' => '7504', 'name' => 'Pahuwato', 'type' => 'Kabupaten', 'province' => 'Gorontalo'],
            ['code' => '7505', 'name' => 'Gorontalo Utara', 'type' => 'Kabupaten', 'province' => 'Gorontalo'],
            ['code' => '7571', 'name' => 'Gorontalo', 'type' => 'Kota', 'province' => 'Gorontalo'],
            ['code' => '7601', 'name' => 'Pasangkayu (Mamuju Utara)', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '7602', 'name' => 'Mamuju', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '7603', 'name' => 'Mamasa', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '7604', 'name' => 'Polewali Mandar', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '7605', 'name' => 'Majene', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '7606', 'name' => 'Mamuju Tengah', 'type' => 'Kabupaten', 'province' => 'Sulawesi Barat'],
            ['code' => '8101', 'name' => 'Maluku Tengah', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8102', 'name' => 'Maluku Tenggara', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8103', 'name' => 'Maluku Tenggara Barat', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8104', 'name' => 'Buru', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8105', 'name' => 'Seram Bagian Timur', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8106', 'name' => 'Seram Bagian Barat', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8107', 'name' => 'Kepulauan Aru', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8108', 'name' => 'Maluku Barat Daya', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8109', 'name' => 'Buru Selatan', 'type' => 'Kabupaten', 'province' => 'Maluku'],
            ['code' => '8171', 'name' => 'Ambon', 'type' => 'Kota', 'province' => 'Maluku'],
            ['code' => '8172', 'name' => 'Tual', 'type' => 'Kota', 'province' => 'Maluku'],
            ['code' => '8201', 'name' => 'Halmahera Barat', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8202', 'name' => 'Halmahera Tengah', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8203', 'name' => 'Halmahera Utara', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8204', 'name' => 'Halmahera Selatan', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8205', 'name' => 'Kepulauan Sula', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8206', 'name' => 'Halmahera Timur', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8207', 'name' => 'Pulau Morotai', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8208', 'name' => 'Pulau Taliabu', 'type' => 'Kabupaten', 'province' => 'Maluku Utara'],
            ['code' => '8271', 'name' => 'Ternate', 'type' => 'Kota', 'province' => 'Maluku Utara'],
            ['code' => '8272', 'name' => 'Tidore Kepulauan', 'type' => 'Kota', 'province' => 'Maluku Utara'],
            ['code' => '9101', 'name' => 'Merauke', 'type' => 'Kabupaten', 'province' => 'Papua Selatan'],
            ['code' => '9102', 'name' => 'Jayawijaya', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9103', 'name' => 'Jayapura', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9104', 'name' => 'Nabire', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9105', 'name' => 'Kepulauan Yapen', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9106', 'name' => 'Biak Numfor', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9107', 'name' => 'Paniai', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9108', 'name' => 'Puncak Jaya', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9109', 'name' => 'Mimika', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9110', 'name' => 'Sarmi', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9111', 'name' => 'Keerom', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9112', 'name' => 'Pegunungan Bintang', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9113', 'name' => 'Yahukimo', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9114', 'name' => 'Tolikara', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9115', 'name' => 'Waropen', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9116', 'name' => 'Boven Digoel', 'type' => 'Kabupaten', 'province' => 'Papua Selatan'],
            ['code' => '9117', 'name' => 'Mappi', 'type' => 'Kabupaten', 'province' => 'Papua Selatan'],
            ['code' => '9118', 'name' => 'Asmat', 'type' => 'Kabupaten', 'province' => 'Papua Selatan'],
            ['code' => '9119', 'name' => 'Supiori', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9120', 'name' => 'Mamberamo Raya', 'type' => 'Kabupaten', 'province' => 'Papua'],
            ['code' => '9121', 'name' => 'Mamberamo Tengah', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9122', 'name' => 'Yalimo', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9123', 'name' => 'Lanny Jaya', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9124', 'name' => 'Nduga', 'type' => 'Kabupaten', 'province' => 'Papua Pegunungan'],
            ['code' => '9125', 'name' => 'Puncak', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9126', 'name' => 'Dogiyai', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9127', 'name' => 'Intan Jaya', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9128', 'name' => 'Deiyai', 'type' => 'Kabupaten', 'province' => 'Papua Tengah'],
            ['code' => '9171', 'name' => 'Jayapura', 'type' => 'Kota', 'province' => 'Papua'],
            ['code' => '9201', 'name' => 'Sorong', 'type' => 'Kabupaten', 'province' => 'Papua Barat Daya'],
            ['code' => '9202', 'name' => 'Manokwari', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9203', 'name' => 'Fakfak', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9204', 'name' => 'Sorong Selatan', 'type' => 'Kabupaten', 'province' => 'Papua Barat Daya'],
            ['code' => '9205', 'name' => 'Raja Ampat', 'type' => 'Kabupaten', 'province' => 'Papua Barat Daya'],
            ['code' => '9206', 'name' => 'Teluk Bintuni', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9207', 'name' => 'Teluk Wondama', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9208', 'name' => 'Kaimana', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9209', 'name' => 'Tambrauw', 'type' => 'Kabupaten', 'province' => 'Papua Barat Daya'],
            ['code' => '9210', 'name' => 'Maybrat', 'type' => 'Kabupaten', 'province' => 'Papua Barat Daya'],
            ['code' => '9211', 'name' => 'Manokwari Selatan', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9212', 'name' => 'Pegunungan Arfak', 'type' => 'Kabupaten', 'province' => 'Papua Barat'],
            ['code' => '9271', 'name' => 'Sorong', 'type' => 'Kota', 'province' => 'Papua Barat Daya'],
        ];

        foreach ($regencies as $regency) {
            Regency::create($regency);
        }
    }
}