<?php

namespace Database\Seeders;

use App\Models\RegistrationPath;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegistrationPathSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kategoris = DB::table('kategori_jalurs')->pluck('id', 'nama');
        $now = now();

        $paths = [
            // ===== SELEKSI NASIONAL (kategori_id = 1) =====
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBP',
                'name' => 'Seleksi Nasional Berdasarkan Prestasi',
                'description' => 'Jalur seleksi nasional berdasarkan prestasi akademik dan non-akademik siswa.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-02-28',
                'fee' => 250000,
                'color' => 'primary',
                'quota' => 500,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBT',
                'name' => 'Seleksi Nasional Berdasarkan Tes',
                'description' => 'Jalur seleksi nasional berdasarkan hasil tes kemampuan akademik.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-04-30',
                'fee' => 300000,
                'color' => 'success',
                'quota' => 800,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBP_PENDIDIKAN',
                'name' => 'SNBP Jalur Pendidikan',
                'description' => 'Jalur seleksi nasional bagi lulusan dari sekolah mitra.',
                'registration_start' => '2026-01-20',
                'registration_end' => '2026-03-15',
                'fee' => 200000,
                'color' => 'primary',
                'quota' => 300,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBT_SAINTEK',
                'name' => 'SNBT Kelompok Sains & Teknologi',
                'description' => 'Jalur seleksi untuk peminatan bidang sains, teknologi, teknik, dan matematika.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-05-15',
                'fee' => 325000,
                'color' => 'info',
                'quota' => 450,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBT_SOSHUM',
                'name' => 'SNBT Kelompok Sosial & Humaniora',
                'description' => 'Jalur seleksi untuk peminatan bidang sosial, ekonomi, hukum, dan humaniora.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-05-15',
                'fee' => 325000,
                'color' => 'warning',
                'quota' => 450,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Nasional'] ?? 1,
                'code' => 'SNBT_CAMPURAN',
                'name' => 'SNBT Kelompok Campuran',
                'description' => 'Jalur seleksi untuk peminatan bidang campuran sains, teknologi, sosial, dan humaniora.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-05-01',
                'fee' => 350000,
                'color' => 'secondary',
                'quota' => 350,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== SELEKSI MANDIRI (kategori_id = 2) =====
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI',
                'name' => 'Jalur Mandiri Reguler',
                'description' => 'Jalur pendaftaran mandiri reguler yang diselenggarakan oleh perguruan tinggi.',
                'registration_start' => '2026-05-01',
                'registration_end' => '2026-07-31',
                'fee' => 500000,
                'color' => 'warning',
                'quota' => 300,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI_TUITION',
                'name' => 'Jalur Mandiri Beasiswa UKT',
                'description' => 'Jalur mandiri dengan penyesuaian UKT berdasarkan kemampuan ekonomi orang tua.',
                'registration_start' => '2026-05-15',
                'registration_end' => '2026-08-15',
                'fee' => 350000,
                'color' => 'success',
                'quota' => 400,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI_KIP',
                'name' => 'Jalur Mandiri KIP Kuliah',
                'description' => 'Jalur mandiri khusus bagi penerima Kartu Indonesia Pintar (KIP) Kuliah.',
                'registration_start' => '2026-05-01',
                'registration_end' => '2026-08-30',
                'fee' => 100000,
                'color' => 'info',
                'quota' => 200,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI_INTERNASIONAL',
                'name' => 'Jalur Mandiri Program Internasional',
                'description' => 'Jalur mandiri untuk program studi berkelas internasional dengan pengantar bahasa Inggris.',
                'registration_start' => '2026-04-01',
                'registration_end' => '2026-07-15',
                'fee' => 750000,
                'color' => 'danger',
                'quota' => 150,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI_VOKASI',
                'name' => 'Jalur Mandiri Vokasi (D3/D4)',
                'description' => 'Jalur mandiri khusus untuk program diploma (vokasi) yang berorientasi praktik kerja.',
                'registration_start' => '2026-05-01',
                'registration_end' => '2026-08-20',
                'fee' => 400000,
                'color' => 'primary',
                'quota' => 250,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Mandiri'] ?? 2,
                'code' => 'MANDIRI_SORE',
                'name' => 'Jalur Mandiri Kelas Karyawan (Sore)',
                'description' => 'Jalur mandiri bagi karyawan dengan perkuliahan di luar jam kerja (sore/malam).',
                'registration_start' => '2026-06-01',
                'registration_end' => '2026-09-15',
                'fee' => 450000,
                'color' => 'secondary',
                'quota' => 200,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== SELEKSI PRESTASI (kategori_id = 3) =====
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI',
                'name' => 'Jalur Prestasi Akademik',
                'description' => 'Jalur pendaftaran bagi calon mahasiswa dengan prestasi akademik unggul.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-06-30',
                'fee' => 200000,
                'color' => 'info',
                'quota' => 200,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI_OLAHRAGA',
                'name' => 'Jalur Prestasi Olahraga',
                'description' => 'Jalur bagi calon mahasiswa dengan prestasi di bidang olahraga tingkat nasional/internasional.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-07-15',
                'fee' => 150000,
                'color' => 'success',
                'quota' => 100,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI_SENI',
                'name' => 'Jalur Prestasi Seni & Budaya',
                'description' => 'Jalur bagi calon mahasiswa dengan prestasi di bidang seni, musik, tari, dan teater.',
                'registration_start' => '2026-02-01',
                'registration_end' => '2026-07-15',
                'fee' => 150000,
                'color' => 'danger',
                'quota' => 100,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI_KEAGAMAAN',
                'name' => 'Jalur Prestasi Keagamaan',
                'description' => 'Jalur bagi calon mahasiswa dengan prestasi di bidang keagamaan dan hafidz Al-Quran.',
                'registration_start' => '2026-02-01',
                'registration_end' => '2026-06-30',
                'fee' => 125000,
                'color' => 'primary',
                'quota' => 80,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI_SAINS',
                'name' => 'Jalur Prestasi Sains & Riset',
                'description' => 'Jalur bagi calon mahasiswa dengan prestasi di olimpiade sains, penelitian, dan karya ilmiah.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-05-31',
                'fee' => 175000,
                'color' => 'warning',
                'quota' => 120,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Prestasi'] ?? 3,
                'code' => 'PRESTASI_KEWIRAUSAHAAN',
                'name' => 'Jalur Prestasi Kewirausahaan',
                'description' => 'Jalur bagi calon mahasiswa dengan prestasi di bidang wirausaha dan startup.',
                'registration_start' => '2026-02-01',
                'registration_end' => '2026-07-31',
                'fee' => 200000,
                'color' => 'info',
                'quota' => 90,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== SELEKSI INTERNASIONAL (kategori_id = 4) =====
            [
                'kategori_jalur_id' => $kategoris['Seleksi Internasional'] ?? 4,
                'code' => 'INTERNASIONAL',
                'name' => 'Jalur Internasional (IUP)',
                'description' => 'Jalur pendaftaran bagi calon mahasiswa internasional dengan kurikulum global.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-07-31',
                'fee' => 1000000,
                'color' => 'primary',
                'quota' => 100,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Internasional'] ?? 4,
                'code' => 'INTERNASIONAL_SAT',
                'name' => 'Jalur Internasional (SAT/ACT)',
                'description' => 'Jalur bagi calon mahasiswa dengan skor SAT atau ACT internasional.',
                'registration_start' => '2026-04-01',
                'registration_end' => '2026-08-15',
                'fee' => 850000,
                'color' => 'success',
                'quota' => 75,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Internasional'] ?? 4,
                'code' => 'INTERNASIONAL_EXCHANGE',
                'name' => 'Jalur Pertukaran Mahasiswa',
                'description' => 'Jalur bagi calon mahasiswa dari program pertukaran internasional.',
                'registration_start' => '2026-03-15',
                'registration_end' => '2026-06-30',
                'fee' => 500000,
                'color' => 'warning',
                'quota' => 50,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Internasional'] ?? 4,
                'code' => 'INTERNASIONAL_BEASISWA',
                'name' => 'Jalur Beasiswa Internasional',
                'description' => 'Jalur bagi calon mahasiswa asing dengan beasiswa penuh dari pemerintah/sponsor.',
                'registration_start' => '2026-02-01',
                'registration_end' => '2026-05-30',
                'fee' => 200000,
                'color' => 'danger',
                'quota' => 30,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Internasional'] ?? 4,
                'code' => 'INTERNASIONAL_DIPLOMA',
                'name' => 'Jalur Double Degree Internasional',
                'description' => 'Jalur program double degree dengan universitas mitra di luar negeri.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-06-15',
                'fee' => 1500000,
                'color' => 'info',
                'quota' => 40,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ===== SELEKSI KERJASAMA (kategori_id = 5) =====
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'ALIH_JENJANG',
                'name' => 'Alih Jenjang (Transfer)',
                'description' => 'Jalur pendaftaran bagi calon mahasiswa pindahan atau alih jenjang dari perguruan tinggi lain.',
                'registration_start' => null,
                'registration_end' => null,
                'fee' => 400000,
                'color' => 'secondary',
                'quota' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_INDUSTRI',
                'name' => 'Jalur Kerjasama Industri',
                'description' => 'Jalur pendaftaran melalui kerjasama dengan perusahaan mitra (ikatan dinas).',
                'registration_start' => '2026-04-01',
                'registration_end' => '2026-08-31',
                'fee' => 300000,
                'color' => 'primary',
                'quota' => 150,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_PEMDA',
                'name' => 'Jalur Kerjasama Pemda',
                'description' => 'Jalur pendaftaran melalui kerjasama beasiswa dengan pemerintah daerah asal.',
                'registration_start' => '2026-02-01',
                'registration_end' => '2026-06-30',
                'fee' => 150000,
                'color' => 'success',
                'quota' => 200,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_PESANTREN',
                'name' => 'Jalur Kerjasama Pondok Pesantren',
                'description' => 'Jalur khusus bagi lulusan pondok pesantren mitra dengan kurikulum terpadu.',
                'registration_start' => '2026-03-01',
                'registration_end' => '2026-07-15',
                'fee' => 250000,
                'color' => 'warning',
                'quota' => 180,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_SMA',
                'name' => 'Jalur Kerjasama SMA/SMK Mitra',
                'description' => 'Jalur khusus bagi lulusan SMA/SMK yang telah menjalin kerjasama dengan kampus.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-04-30',
                'fee' => 200000,
                'color' => 'info',
                'quota' => 300,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_KORPORASI',
                'name' => 'Jalur Kerjasama Korporasi',
                'description' => 'Jalur bagi karyawan/keluarga dari perusahaan korporasi mitra kampus.',
                'registration_start' => '2026-05-01',
                'registration_end' => '2026-09-30',
                'fee' => 350000,
                'color' => 'dark',
                'quota' => 120,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kategori_jalur_id' => $kategoris['Seleksi Kerjasama'] ?? 5,
                'code' => 'KERJASAMA_DAERAH_3T',
                'name' => 'Jalur Afirmasi Daerah 3T',
                'description' => 'Jalur afirmasi bagi calon mahasiswa dari daerah tertinggal, terdepan, dan terluar.',
                'registration_start' => '2026-01-15',
                'registration_end' => '2026-08-31',
                'fee' => 50000,
                'color' => 'danger',
                'quota' => 250,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Hapus data lama dulu biar bersih
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        DB::table('registration_paths')->truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        foreach ($paths as $path) {
            RegistrationPath::create($path);
        }

        $this->command->info('30 registration paths seeded successfully for infinite scroll testing!');
    }
}